/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IfxFeedbackWidget {
        "appName": string;
    }
}
declare global {
    interface HTMLIfxFeedbackWidgetElement extends Components.IfxFeedbackWidget, HTMLStencilElement {
    }
    var HTMLIfxFeedbackWidgetElement: {
        prototype: HTMLIfxFeedbackWidgetElement;
        new (): HTMLIfxFeedbackWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "ifx-feedback-widget": HTMLIfxFeedbackWidgetElement;
    }
}
declare namespace LocalJSX {
    interface IfxFeedbackWidget {
        "appName"?: string;
    }
    interface IntrinsicElements {
        "ifx-feedback-widget": IfxFeedbackWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ifx-feedback-widget": LocalJSX.IfxFeedbackWidget & JSXBase.HTMLAttributes<HTMLIfxFeedbackWidgetElement>;
        }
    }
}
