name: "publish npm"

on: push

jobs:
 publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --access public
      # - run: npm install
      # - run: npm run build
        env:
            NODE_AUTH_TOKEN: ${{secrets.IFX_FEEDBACK_WIDGET}}
